# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qT4fhHbA5IzGAzfY8WCyFE3xg5VSrmbj
"""

import time

# Iniciar con las zonas de temperatura
zonas = {}
temperaturas = {}
horarios = {}

def ConfiguracionZonas():
    num_zonas = int(input("Cuántas zonas deseas configurar? "))
    for _ in range(num_zonas):
        zona = input("Ingresa el nombre de la zona: ")
        temperatura = float(input("Ingresa la temperatura deseada para :" + zona))
        zonas[zona] = 22  # Temperatura inicial
        temperaturas[zona] = temperatura

def MostrarTemperaturas():
    for zona, temp in zonas.items():
        print(zona + " " + str(temp) + "°C - Deseada:" + str(temperaturas[zona]) + "°C")

def AjustarTemperatura():
    zona = input("Ingresa el nombre de la zona a ajustar: ")
    if zona in zonas:
        NuevaTemp = float(input("Ingresa la nueva temperatura deseada para : " + zona))
        temperaturas[zona] = NuevaTemp
    else:
        print("Zona no encontrada")

def ProgramarHorarios():
    zona = input("Ingresa el nombre de la zona para programar: ")
    if zona in zonas:
        hora = input("Ingresa la hora en formato HH:MM (En 24 horas) para ajustar la temperatura: ")
        temp = float(input("Ingresa la temperatura deseada para " + zona + " a las " + hora + ": "))
        if zona not in horarios:
            horarios[zona] = []
        horarios[zona].append((hora, temp))
    else:
        print("Zona no encontrada")

def Monitoreo():
    while True:
        HoraActual = time.strftime("%H:%M")
        for zona in zonas:
            if zona in horarios:
                for horario, temp in horarios[zona]:
                    if HoraActual == horario:
                        zonas[zona] = temp
            if zonas[zona] < 22:
                zonas[zona] = 22
            elif zonas[zona] > 22:
                zonas[zona] = 22


while True:
    print("Sistema de Control de Temperatura")
    print("1. Configurar zonas")
    print("2. Mostrar temperaturas")
    print("3. Ajustar temperatura")
    print("4. Programar horarios")
    print("5. Salir")
    opcion = input("Selecciona una opción: ")

    if opcion == "1":
        ConfiguracionZonas()
    elif opcion == "2":
        MostrarTemperaturas()
    elif opcion == "3":
        AjustarTemperatura()
    elif opcion == "4":
        ProgramarHorarios()
    elif opcion == "5":
        print("Gracias nos vemos pronto ;)")
        break
    else:
        print("Opción no válida, por favor intenta de nuevo")